version: "3.9"
services:
  billing_db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=billing
      - POSTGRES_PASSWORD=billing321
      - POSTGRES_DB=billing
    ports:
      - '5432:5432'