server:
  port: 9090

spring:
  application.name: lb
  profiles:
    active: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


encryption:
  secret-key: hr8$AY!A%iJMcb9ukcIaNaDEzE16@p
  algorithm: AES

decryption-time: 10